run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  allow-parallel-runners: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  varnamelen:
    ignore-names:
      - ok
      - err
      - id
      - db
      - i
      - tx # transaction
      - tC # test case
      - wg # wait group, wargaming
  gofumpt:
    module-path: github.com/opoccomaxao/wblitz-watcher
    extra-rules: true
  gci:
    custom-order: false
    sections:
      - standard
      - default
      - prefix(github.com/opoccomaxao/wblitz-watcher)
  godot:
    exclude:
      - "^@*"
  errcheck:
    exclude-functions:
      - (*github.com/gin-gonic/gin.Error).SetType
      - (*github.com/gin-gonic/gin.Context).AbortWithError
      - (*github.com/gin-gonic/gin.Context).Error
  gosec:
    excludes:
      - G202 # SQL query construction using placeholders

linters:
  disable-all: true
  enable:
    # default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # nondefault
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - deadcode
    - decorder
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    # - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagalign
    - tenv
    - testableexamples
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint
  fast: false

issues:
  fix: true
  new: false
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
    - source: "^//"
      linters:
        - lll
