name: Build and Push

on:
  push:
    branches:
      - docker
  workflow_dispatch: {}

env:
  project: wbwatcher
  deploy_tag: latest
  username: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: docker auth
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: go setup
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: go build
        run: go build -buildvcs -o $project main.go
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64

      - name: docker build and push
        run: |
          echo "Pushing $deploy_tag"
          docker build -t $username/$project:$deploy_tag .
          docker push $username/$project:$deploy_tag

          tag=`git describe --tags --exact-match || echo ""`
          if [ "$tag" ]
          then
            echo "Pushing $tag"
            docker image tag $username/$project:$deploy_tag $username/$project:$tag
            docker push $username/$project:$tag
          fi
